engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 150
  eslint:
    enabled: true
    channel: "eslint-3"
    checks:
      import/no-unresolved:
        enabled: false
    enabled: true
exclude_paths:
- examples/
- node_modules/
